### ISSUE TITLE
MathJax not parsed with littlefoot

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [goblindegook/littlefoot#362] opened 2020-06-18 10:24 UTC
Hi,

I'm using the [Academic theme](https://sourcethemes.com/academic/) which allows me to write math expressions using [MathJax](https://www.mathjax.org). Without `littlefoot` I can write math (LaTeX) expressions also in footnotes and they are correctly parsed and rendered. With `littlefoot`, however, MathJax expressions are not being interpreted in footnotes.

Is there any solution for this?

Thanks!

**Comment by goblindegook** [comment] 2020-06-18 17:56
Can you post a sample of the HTML generated by the theme, or point me to an example page of it in action, please?

**Comment by rodrigoalcarazdelaosa** [comment] 2020-06-18 18:35
> Can you post a sample of the HTML generated by the theme, or point me to an example page of it in action, please?

The relevant html generated is:
```
<span class="littlefoot-footnote__host">
	<button class="littlefoot-footnote__button littlefoot-footnote__button__ellipsis is-active" id="fnref:6" title="See Footnote 6" aria-controls="fncontent:6" aria-expanded="true" aria-label="Footnote 6" rel="footnote" data-footnote-button="" data-footnote-id="6" data-footnote-number="6">
		<svg viewBox="0 0 31 6" preserveAspectRatio="xMidYMid">
			<circle r="3" cx="3" cy="3" fill="white"></circle>
			<circle r="3" cx="15" cy="3" fill="white"></circle>
			<circle r="3" cx="27" cy="3" fill="white"></circle>
		</svg>
	</button>
	<aside class="littlefoot-footnote is-positioned-bottom is-scrollable is-active" id="fncontent:6" alt="Footnote 6" aria-live="polite" data-footnote-popover="" data-footnote-id="6" data-footnote-position="bottom" style="transform-origin: 46.8213% 0px; max-width: 687px; left: -13.3242px;">
		<div class="littlefoot-footnote__wrapper" style="max-width: 601px;">
			<div class="littlefoot-footnote__content" tabindex="0" style="max-height: 240px;">
				<p>De nuevo para poner estos datos en perspectiva, un avión comercial tarda unos 10 minutos en alcanzar su velocidad de crucero, que son unos 900$\thinspace$km/h. Es decir, en el mismo tiempo, el Falcon 9 es capaz de alcanzar una velocidad unas 30 veces superior a la de crucero de un avión comercial. 
				</p>
			</div>
		</div>
		<div class="littlefoot-footnote__tooltip" style="left: 6.12716%;"></div>
	</aside>
</span>
```

Especially this part of the footnote (this is just an example but it's representative): `900$\thinspace$km/h`. To write math expressions with MathJax we have to enclose them between `$...$` for inline or `$$...$$` for block display. The thing is that those expressions are being correctly parsed by MathJax with normal Goldmark footnotes.

**Comment by goblindegook** [comment] 2020-06-18 18:39
What does it look like before littlefoot is executed? I'm particularly interested in the list items at the bottom of the document, it's possible littlefoot is overlooking a few critical tags there.

**Comment by rodrigoalcarazdelaosa** [comment] 2020-06-18 18:41
> What does it look like before littlefoot is executed? I'm particularly interested in the list items at the bottom of the document, it's possible littlefoot is overlooking a few critical tags there.

The item associated with that particular footnote is this one:
```
<li id="fn:6" role="doc-endnote">
<p>De nuevo para poner estos datos en perspectiva, un avión comercial tarda unos 10 minutos en alcanzar su velocidad de crucero, que son unos 900<mjx-container class="MathJax CtxtMenu_Attached_0" jax="CHTML" role="presentation" tabindex="0" ctxtmenu_counter="30" style="font-size: 91.6%; position: relative;"><mjx-math class="MJX-TEX" aria-hidden="true"><mjx-mstyle><mjx-mspace style="width: 0.167em;"></mjx-mspace></mjx-mstyle></mjx-math><mjx-assistive-mml role="presentation" unselectable="on" display="inline"><math xmlns="http://www.w3.org/1998/Math/MathML"><mstyle scriptlevel="0"><mspace width="thinmathspace"></mspace></mstyle></math></mjx-assistive-mml></mjx-container>km/h. Es decir, en el mismo tiempo, el Falcon 9 es capaz de alcanzar una velocidad unas 30 veces superior a la de crucero de un avión comercial. <a href="#fnref:6" class="footnote-backref" role="doc-backlink">↩︎</a></p>
</li>
```

**Comment by rodrigoalcarazdelaosa** [comment] 2020-06-18 18:46
> ```
> <li id="fn:6" role="doc-endnote">
> <p>De nuevo para poner estos datos en perspectiva, un avión comercial tarda unos 10 minutos en alcanzar su velocidad de crucero, que son unos 900<mjx-container class="MathJax CtxtMenu_Attached_0" jax="CHTML" role="presentation" tabindex="0" ctxtmenu_counter="30" style="font-size: 91.6%; position: relative;"><mjx-math class="MJX-TEX" aria-hidden="true"><mjx-mstyle><mjx-mspace style="width: 0.167em;"></mjx-mspace></mjx-mstyle></mjx-math><mjx-assistive-mml role="presentation" unselectable="on" display="inline"><math xmlns="http://www.w3.org/1998/Math/MathML"><mstyle scriptlevel="0"><mspace width="thinmathspace"></mspace></mstyle></math></mjx-assistive-mml></mjx-container>km/h. Es decir, en el mismo tiempo, el Falcon 9 es capaz de alcanzar una velocidad unas 30 veces superior a la de crucero de un avión comercial. <a href="#fnref:6" class="footnote-backref" role="doc-backlink">↩︎</a></p>
> </li>
> ```

Notice the `mjx-container`

**Comment by goblindegook** [comment] 2020-06-18 19:28
Seems like an issue handling the `mjx-container` element when littlefoot clones the DOM node. Thanks for reporting it.

**Comment by goblindegook** [comment] 2020-06-18 23:09
I'm not able to reproduce the issue, I'm afraid. I can confirm littlefoot renders MathML correctly inside a popover. For instance:

<img width="302" alt="image" src="https://user-images.githubusercontent.com/285497/85080170-6a17c000-b1c0-11ea-9e08-4ab7fa8362bb.png">

Your example, on the other hand, doesn't seem to render a formula at all, even if I put it on an isolated document without littlefoot. Can you confirm you have the correct markup?

**Comment by rodrigoalcarazdelaosa** [comment] 2020-06-19 09:42
> **Edit:** I hadn't noticed it just renders a space --- which does appear within the popover in my tests.

I'm sorry about the example choice, clearly not the most illustrative 🙄🤦‍♂️.

> I'm not familiar with how the theme works, but is it possible that the process to translate TeX into the MathJax tags is done in JavaScript and is somehow interrupted by littlefoot's initialization? Maybe it's worth trying to initialise littlefoot either before or after MathJax is generated, if that's an option.

Problem with this is that `MathJax` is loaded in the `head`, so if I want to load littlefoot before, then I'd have to put it in the `head` too. I'll see what I can do anyway.

Thanks!

**Comment by goblindegook** [comment] 2020-06-19 10:07
If I understood correctly, you probably need to run the `littlefoot()` function only after MathJax fully processes the document markup.

The problem is that when you run the function, littlefoot copies the footnote elements that are used for the popovers into memory, and because they're not in the document, the MathJax library never gets to transform them.

So either this function has to run after MathJax finishes processing, or you need to run MathJax manually for each popover so their contents are formatted (using the `activateCallback` option, for example).

**Comment by rodrigoalcarazdelaosa** [comment] 2020-06-19 10:33
Thanks @goblindegook I'll see what I can do. I'm exploring other solutions as well (such as [this one](https://www.vojtech.net/posts/hugo-footnotes-popup/), although it doesn't have scrollable footnotes yet, and I also prefer your _ellipsis_ symbol for the footnotes instead of numbers).

**Comment by rodrigoalcarazdelaosa** [comment] 2020-06-19 13:19
> Thanks @goblindegook I'll see what I can do. I'm exploring other solutions as well (such as [this one](https://www.vojtech.net/posts/hugo-footnotes-popup/), although it doesn't have scrollable footnotes yet, and I also prefer your _ellipsis_ symbol for the footnotes instead of numbers).

Related to this, your script changes footnote numbers to a specific symbol. How hard is to do that (just that)? Also, can that symbol be easily customized (for example change it to a [circled plus](https://www.w3schools.com/charsets/tryit.asp?deci=8853&ent=oplus), [like Tufte CSS does](https://edwardtufte.github.io/tufte-css/)?

**Comment by goblindegook** [comment] 2020-06-19 13:25
Yes, see the [`buttonTemplate`](https://github.com/goblindegook/littlefoot#buttontemplate) option. Something like:

```html
<button
  aria-controls="fncontent:<% id %>"
  aria-expanded="false"
  aria-label="Footnote <% number %>"
  class="littlefoot-footnote__button"
  id="<% reference %>"
  rel="footnote"
  title="See Footnote <% number %>"
>&oplus;</button>
```

The number is available to you as well, if you prefer to keep it, simply use the `<% number %>` token.

**Comment by goblindegook** [comment] 2020-06-28 01:26
MathJax docs recommend running `MathJax.typeset()` to handle dynamic content added to the page post initialisation, so you can use it via the `activateCallback` setting:

```javascript
littlefoot({
  activateCallback: function () {
    MathJax.typeset()
  }
})
```

Hope this helps. Closing the issue as there doesn't seem to be a problem with the library itself.

**Closed by goblindegook** 2020-06-28 01:26 UTC
