### ISSUE TITLE
Footnote buttons appear above the popover on small screens

### ISSUE THREAD

**Issue by pangolinbubonique** [goblindegook/littlefoot#658] opened 2021-01-06 15:05 UTC
Hi,‎

The bottom footnotes (on screens with narrow width) seem to be designed so that they occupy the ‎whole width. But I fail to obtain this result.‎

I tried the example you give here :‎
https://codepen.io/goblindegook/pen/oPNzGE

it works fine on the codepen preview :
![codepen](https://user-images.githubusercontent.com/77063088/103781884-28087b80-5037-11eb-9cf2-167f9bd15280.jpg)

But when running the code in a browser from an independent html file (simple copy/paste of the code), ‎the bottom footnotes leave some empty space on the right. Tested on PC desktop, on chrome and firefox, same behaviour.‎
![chrome](https://user-images.githubusercontent.com/77063088/103783371-ec6eb100-5038-11eb-8912-8ab3723cee69.jpg)

Maybe this comes from the way the body width is taken in argument in the .js ? The .css seems ok. I failed to solve the problem...

**Comment by goblindegook** [comment] 2021-01-08 01:46
Hi @pangolinbubonique, which version of littlefoot are you running? Seems to have something to do with the space reserved for the scrollbar. Anyway, the CSS changed a bit in the current prerelease, can you check if the issue is still present, please?

**Comment by pangolinbubonique** [comment] 2021-01-08 11:36
Hi, thanks it works with the last versions !

I had used those ones, given in the codepen example : 
https://unpkg.com/littlefoot/dist/littlefoot.css
https://unpkg.com/littlefoot/dist/littlefoot.js

**Comment by pangolinbubonique** [comment] 2021-01-08 11:49
But there is another problem, in the last version there is a problem of superposition, when clicked on a button, the other buttons appear above the footnote : 
![chrome](https://user-images.githubusercontent.com/77063088/104012252-cae40580-51af-11eb-8f26-8ebab6de3b16.jpg)

here the button of footnote 2 should be hidden with the rest of the text, but it stays visible.

**Comment by goblindegook** [comment] 2021-01-08 12:34
Thanks, @pangolinbubonique, glad to hear the upcoming version will address it. The ones in the example are the current stable one, they'll be updated once the new version is released.

Thanks for the heads up about the superimposed buttons, I can confirm it's happening, I'll have it fixed.

**Comment by goblindegook** [comment] 2021-01-08 18:06
Fix released in version 4.0.0-5 (caveat: this is still a prerelease build).

**Closed by goblindegook** 2021-01-08 18:06 UTC
Labels: bug

**Comment by pangolinbubonique** [comment] 2021-01-10 22:29
Thank you, indeed it is corrected for small screens :-) but I just realized that the buttons were still on first plane for big screens. When you add z-index:1 in the css also, in the general popover definition, it works.
